### PR TITLE
change tick to pass second arg

### PR DESCRIPTION
**Pull request by ikemonn**
@makinoy I changed 'tick' to pass second arg. Please review.

### CODE REVIEW

**Comment by makinoy** [comment]
Hi @ikemonn,

I have questions for package.json. Why did you change the url of the repository and the version of 'node-dogstatsd' ?

**Comment by ikemonn** [comment]
@makinoy 
I want to use 'incrementBy' method which is included latest GitHub source code of 'node-dogstatsd'.
However npm's does not have the method.
So, I changed.

**Comment by makinoy** [comment]
@ikemonn,

It seems to have "#update_stats(stat, count, sample_rate?, tags?)". Please try it.

Thanks

**Comment by makinoy** [comment]
Thanks @ikemonn,

I consumed your change. See https://github.com/makinoy/libs-dogstatsd/commit/8fc562e2606a041b70360e357735000cda5131d6

**Pull request closed without merging**
